apiVersion: v1
kind: Service
metadata:
  name: story-app-service
spec:
  selector:
    app: story
  type: LoadBalancer
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: estonian/kubernetes-story-demo:ver2
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          hostPath:
            path: /data
            type: DirectoryOrCreate
